# docker-compose.yml
version: '3.8'

services:
  frontend:
    image: nginx:alpine
    container_name: jogo-digitacao-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro        # Seus arquivos estáticos
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # <-- Monta seu arquivo de configuração
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jogo-digitacao-backend
    # Não precisa mais expor a porta 3000 do backend para o host (ports)
    # Se você usar o Nginx como proxy reverso para o backend.
    # No entanto, para desenvolvimento e testes diretos, ainda pod e ser útil manter.
    # ports:
    #   - "3000:3000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - PORT=3000
      - DATABASE_PATH=/app/data/database.sqlite
    restart: always
    depends_on:
      - frontend